build:
  image: reg.firstshare.cn/base/fs-golang:1.13
  stage: go_build
  tags:
    - docker-build
  script:
    - "go env -w GOPROXY=https://goproxy.cn,direct"
    - "CGO_ENABLED=0"
    - "GOOS=linux"
    - " go build -o grafana-manager ./cmd/manager"
    - "chmod +x grafana-manager"

ksc_import:
  stage: import
  tags:
    - import
  variables:
    GRAFANA_URL: "http://ksc-prod.foneshare.cn/grafana"
  script:
    - grafana-manager --url "http://172.31.107.24:38082/" -u admin -p admin import dashboard ./grafana-dashboard-definitions/common
stages:
  - go_build
  - import
