#cache:
#  paths:
#    - grafana-manager

ksc_k8s1:
  image: reg.firstshare.cn/base/fs-golang:1.13
  stage: go_build
  variables:
    es_url: "http://10.205.41.205:9200"
    es_user: "elastic"
    es_password: "ObUY87jvJNXxHsiL2vBs"
    grafana_url: "http://ksc-prod.foneshare.cn/grafana"
  tags:
    - k8s-deploy
  script:
#    - "go env -w GOPROXY=https://goproxy.cn,direct"
#    - "CGO_ENABLED=0"
#    - "GO111MODULE=on"
#    - "GOOS=linux"
#    - " go build -o grafana-manager ./cmd/manager"
    - "chmod +x grafana-manager"
    - echo ${es_url}
    - sed -i "s#{{\s*ES_URL\s*}}#${es_url}#g" ./grafana-dashboard-definitions/datasource/*.json
    - sed -i "s#{{\s*ES_USER\s*}}#${es_user}#g" ./grafana-dashboard-definitions/datasource/*.json
    - sed -i "s#{{\s*ES_PASSWORD\s*}}#${es_password}#g" ./grafana-dashboard-definitions/datasource/*.json
    - ./grafana-manager --url "${grafana_url}" -u admin -p admin import dashboard ./grafana-dashboard-definitions/common
    - ./grafana-manager --url "${grafana_url}" -u admin -p admin import dashboard ./grafana-dashboard-definitions/k8s
    - ./grafana-manager --url "${grafana_url}" -u admin -p admin import dashboard ./grafana-dashboard-definitions/k8s-system
    - ./grafana-manager --url "${grafana_url}" -u admin -p admin import datasource ./grafana-dashboard-definitions/datasource
ucd_k8s2:
  image: reg.firstshare.cn/base/fs-golang:1.13
  stage: go_build
  variables:
    es_url: "http://10.192.43.205:9200"
    es_user: "elastic"
    es_password: "nXnoM6mVMLbYtD7t5tQD"
    grafana_url: "http://ucd-prod.foneshare.cn/grafana"
  tags:
    - k8s-deploy
  script:
#    - "go env -w GOPROXY=https://goproxy.cn,direct"
#    - "CGO_ENABLED=0"
#    - "GOOS=linux"
#    - " go build -o grafana-manager ./cmd/manager"
    - ls -l
    - "chmod +x grafana-manager"
    - echo ${es_url}
    - sed -i "s#{{\s*ES_URL\s*}}#${es_url}#g" ./grafana-dashboard-definitions/datasource/*.json
    - sed -i "s#{{\s*ES_USER\s*}}#${es_user}#g" ./grafana-dashboard-definitions/datasource/*.json
    - sed -i "s#{{\s*ES_PASSWORD\s*}}#${es_password}#g" ./grafana-dashboard-definitions/datasource/*.json
    - ./grafana-manager --url "${grafana_url}" -u admin -p admin import dashboard ./grafana-dashboard-definitions/common
    - ./grafana-manager --url "${grafana_url}" -u admin -p admin import dashboard ./grafana-dashboard-definitions/k8s
    - ./grafana-manager --url "${grafana_url}" -u admin -p admin import dashboard ./grafana-dashboard-definitions/k8s-system
    - ./grafana-manager --url "${grafana_url}" -u admin -p admin import datasource ./grafana-dashboard-definitions/datasource

stages:
  - go_build
