{
 "title": "k8s监控",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,2m,5m,10m,30m" },
   { "name": "cluster", "query": "k8s1" },
   {
    "name": "host",
    "query": "label_values(node_boot_time_seconds{job=~\"$cluster-node-exporter\"}, host)"
   },
   {
    "name": "app",
    "query": "label_values(jvm_info{job=~\"$cluster-jvm-exporter\"}, app_name)"
   }
  ]
 },
 "panels": [
  { "title": "集群", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "<div style=\"text-align:center;font-size:2em;\">\n<b style=\"color:#5991A7;\">集群:</b> <span style=\"color:#e68a00;\">$cluster</span>\n</div>\n"
  },
  {
   "title": "当前集群可用内存小于5g的节点",
   "type": "graph",
   "description": "10.x为管理系节点内存大于2g可以忽略\n\n忽略以下节点：\n\n5.17-5.56(crm专用节点)\n\n5.201-5.206(master节点)\n\n5.77-5.79(ingress节点)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"$cluster.*\",host!~\"172.17.5.((1[7-9]|2[0-9]|3[0-9]|4[0-9]|5[1-6])|20[1-6]|7[7-9])\"}  < 5368709120",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "15分钟内有重启的应用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, ceil(delta(kube_pod_container_status_restarts_total[15m]) > 0))",
     "legendFormat": "{{pod}} / {{job}}"
    }
   ]
  },
  {
   "title": "宿主机 CPU 负载（$cluster ）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, node_load1{job=~\"$cluster-node-exporter\"})",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "应用CPU使用 排行榜（$cluster）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(rate(container_cpu_usage_seconds_total{container=~\".+\",job=~\"$cluster-node-cadvisor-metrics\"}[$interval]))  by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "应用 内存 使用（$cluster）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_working_set_bytes{container=~\".+\",job=~\"$cluster-node-cadvisor-metrics\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "宿主机",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
     "content": "<div style=\"text-align:center;font-size:2em;\">\n<b style=\"color:#5991A7;\">宿主机:</b> <span style=\"color:#e68a00;\">$host</span>\n</div>\n"
    },
    {
     "title": "CPU 平均负载（Load）",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{host=~\"$host\"}",
       "legendFormat": "1分钟"
      },
      {
       "expr": "node_load5{host=~\"$host\"}",
       "legendFormat": "5分钟"
      },
      {
       "expr": "node_load15{host=~\"$host\"}",
       "legendFormat": "15分钟"
      }
     ]
    },
    {
     "title": "内存使用量",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{host=\"$host\"} - node_memory_MemAvailable_bytes{host=\"$host\"}",
       "legendFormat": "已使用"
      },
      {
       "expr": "node_memory_MemTotal_bytes{host=\"$host\"}",
       "legendFormat": "总内存"
      }
     ]
    },
    {
     "title": "CPU使用",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{host=~\"$host\",mode!=\"idle\"}[$interval]))  by (mode) \r",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "内存使用（按应用）",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(container_memory_working_set_bytes{container=~\".+\", host=\"$host\"}) by (pod))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container=~\".+\", host=\"$host\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "CPU使用（按应用）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\".+\", host=~\"$host\"}[$interval]))  by (pod) \r",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "磁盘IO读写时间",
     "type": "graph",
     "description": "Read time ms 每个磁盘分区读操作花费的秒数\n\nWrite time ms 每个磁盘分区写操作花费的秒数\n\nIO time ms 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted 每个磁盘分区输入/输出操作花费的加权秒数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "s", "label": "读取（-）/写入（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{host=~'$host'}[1m])",
       "legendFormat": "{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{host=~'$host'}[1m])",
       "legendFormat": "{{device}}_写入"
      }
     ]
    },
    {
     "title": "磁盘读写速率（IOPS）",
     "type": "graph",
     "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{host=~'$host'}[1m])",
       "legendFormat": "{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{host=~'$host'}[1m])",
       "legendFormat": "{{device}}_写入"
      }
     ]
    },
    {
     "title": "TCP 连接情况",
     "type": "graph",
     "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{host=~'$host'}",
       "legendFormat": "ESTABLISHED"
      },
      {
       "expr": "node_sockstat_TCP_tw{host=~'$host'}",
       "legendFormat": "TCP_tw"
      },
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{host=~'$host'}[1m])",
       "legendFormat": "ActiveOpens"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{host=~'$host'}[1m])",
       "legendFormat": "PassiveOpens"
      },
      {
       "expr": "node_sockstat_TCP_alloc{host=~'$host'}",
       "legendFormat": "TCP_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{host=~'$host'}",
       "legendFormat": "TCP_inuse"
      }
     ]
    },
    {
     "title": "磁盘读写容量大小",
     "type": "graph",
     "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "Bps", "label": "读取（-）/写入（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{host=~'$host'}[1m])",
       "legendFormat": "{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{host=~'$host'}[1m])",
       "legendFormat": "{{device}}_写入"
      }
     ]
    },
    {
     "title": "各分区可用空间",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{host=~'$host',fstype=~\"ext4|xfs\"}"
      },
      {
       "expr": "1-(node_filesystem_free_bytes{host=~'$host',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{host=~'$host',fstype=~\"ext4|xfs\"})"
      }
     ]
    }
   ]
  }
 ]
}