{
 "title": "pod-jvm-monitor",
 "description": "Dashboard for JVM metrics and Cadvisor metrics",
 "tags": [
  "JVM",
  "pod"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,2m,5m,10m,30m,1h,6h" },
   {
    "name": "namespace",
    "query": "label_values(jvm_info{job=~\"k8s.+-jvm-exporter\"}, namespace)"
   },
   {
    "name": "app",
    "query": "label_values(jvm_info{job=~\"k8s.+-jvm-exporter\", namespace =\"$namespace\"}, app_name)"
   },
   {
    "name": "pod",
    "query": "label_values(jvm_info{job=~\"k8s.+-jvm-exporter\",namespace =\"$namespace\", app_name =\"$app\"}, pod_name)"
   },
   {
    "name": "pod_ip",
    "query": "label_values(jvm_info{job=~\"k8s.+-jvm-exporter\",namespace =\"$namespace\", app_name =\"$app\", pod_name=\"$pod\"}, pod_ip)"
   },
   {
    "name": "host_ip",
    "query": "label_values(jvm_info{job=~\"k8s.+-jvm-exporter\",namespace =\"$namespace\", app_name =\"$app\", pod_name=\"$pod\"}, host_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU使用情况（所有实例）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$app\", pod=\"$pod\",cpu=\"total\"}[$interval]))  by (pod))\n",
     "legendFormat": "current::  {{pod}}"
    },
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$app\",pod!=\"$pod\",cpu=\"total\"}[$interval]))  by (instance, pod))",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "内存使用情况（所有实例）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$app\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "-- 容器（Pod）--",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "content": "<div style=\"text-align:center;\">\n<table style=\"max-width:1200px;text-align:left;margin:0 auto;\">\n<tr style=\"color:#5991A7;\">\n  <th>环境</th>\n  <th>应用</th>\n  <th>Pod名</th>\n  <th>Pod IP</th>\n  <th>宿主机 IP</th>\n</tr>\n<tr style=\"color:#e68a00;\">\n  <td>$namespace</td>\n  <td>$app</td>\n  <td>$pod</td>\n  <td>$pod_ip</td>\n  <td>$host_ip</td>\n</tr>\n</table>\n</div>\n\n\n"
  },
  {
   "title": "CPU使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container=~\".+\", pod=~\"$pod\"}[5m]))  by (pod) / (sum(container_spec_cpu_quota{container=~\".+\", pod=~\"$pod\"}) by (pod) / 100000)) * 100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container=~\".+\",pod=~\"$pod\"}) by (pod) / sum(container_spec_memory_limit_bytes{container=~\".+\",pod=~\"$pod\"}) by (pod))*100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\".+\",pod=~\"$pod\"}) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "启动时间",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(container_start_time_seconds{pod=\"$pod\"}) * 1000"
    }
   ]
  },
  { "title": "容器", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "容器CPU使用情况",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\".+\", pod=~\"$pod\"}[$interval]))  by (pod) \r\n",
     "legendFormat": "使用CPU"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=~\".+\", pod=~\"$pod\"}) by (pod) / 100000",
     "legendFormat": "分配的最大CPU"
    }
   ]
  },
  {
   "title": "容器内存使用情况",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\".+\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "(容器) 使用内存"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container=~\".+\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "(容器) 分配内存"
    }
   ]
  },
  {
   "title": "容器网络流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container=~\".+\",pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "接收流量"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container=~\".+\",pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "发送流量"
    }
   ]
  },
  {
   "title": "容器磁盘流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{container=~\".+\",pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "读取"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container=~\".+\",pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "写入"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  { "title": "-- JVM --", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }, "content": "\n" },
  {
   "title": "内存使用 （Heap 和 NonHeap）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{pod_name=~\"$pod\", pod_ready=\"true\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "内存提交 （Heap 和 NonHeap）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{pod_name=~\"$pod\", pod_ready=\"true\"}",
     "legendFormat": "{{area}}"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{pod_name=~\"$pod\", pod_ready=\"true\"})",
     "legendFormat": "总提交内存"
    }
   ]
  },
  {
   "title": "内存使用（按分区）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pod_name=~\"$pod\", pod_ready=\"true\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pool}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{pod_name=~\"$pod\", pod_ready=\"true\"}[$interval]) ",
     "legendFormat": "{{gc}} Count"
    },
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{pod_name=~\"$pod\", pod_ready=\"true\"}[$interval]) * 1000",
     "legendFormat": "{{gc}} Time"
    }
   ]
  },
  {
   "title": "Threads Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod_name=~\"$pod\", pod_ready=\"true\"}",
     "legendFormat": "current"
    },
    {
     "expr": "tomcat_threadpool_connectioncount{pod_name=~\"$pod\"}",
     "legendFormat": "Tomcat 连接线程数"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{pod_name=~\"$pod\", pod_ready=\"true\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{pod_name=~\"$pod\", pod_ready=\"true\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Number of open file descriptors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "process_max_fds{pod_name=~\"$pod\", pod_ready=\"true\"}",
     "legendFormat": "Maximum number of open file descriptors"
    }
   ]
  }
 ]
}