{
 "title": "LVS",
 "description": "LVS monitor",
 "tags": [
  "PGXL",
  "LVS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "query_result(machine_role{role=\"keepalived\"} * on(host)  group_left(instance) node_load1)"
   }
  ]
 },
 "panels": [
  {
   "title": "TOP CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, node_load1{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\"} - node_memory_MemFree_bytes{host=~\"$host\"} - (node_memory_Cached_bytes{host=~\"$host\"} + node_memory_Buffers_bytes{host=~\"$host\"})",
     "legendFormat": "RAM Used {{host}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\"}",
     "legendFormat": "RAM Total {{host}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host=~\"$host\",device!~'rootfs|tmpfs|overlay|shm'} * 100) / node_filesystem_size_bytes{host=~\"$host\",device!~'rootfs|tmpfs|overlay|shm'})",
     "legendFormat": "{{mountpoint}}{{host}}"
    }
   ]
  },
  {
   "title": "LVS ActiveConn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_ipvs_backend_connections_active{host=~\"$host\"}",
     "legendFormat": "ActiveConn-{{remote_address}}"
    }
   ]
  },
  {
   "title": "LVS InActConn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_ipvs_backend_connections_inactive{host=~\"$host\"}",
     "legendFormat": "InActConn-{{remote_address}}"
    }
   ]
  },
  {
   "title": "LVS InBytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_ipvs_incoming_bytes_total{host=~\"$host\"}[5m])",
     "legendFormat": "LVS InBytes {{host}}"
    }
   ]
  },
  {
   "title": "LVS Receive Total Connection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_ipvs_connections_total{host=~\"$host\"}[5m])",
     "legendFormat": "Connections {{host}}"
    }
   ]
  },
  {
   "title": "LVS InPkts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(node_ipvs_incoming_packets_total{host=~\"$host\"}[5m]) ",
     "legendFormat": "LVS InPkts {{host}}"
    }
   ]
  },
  {
   "title": "LVS Weight",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_ipvs_backend_weight{host=~\"$host\"}",
     "legendFormat": "Weight-{{remote_address}}"
    }
   ]
  }
 ]
}