{
 "title": "Nginx VTS",
 "description": "Show stats from nginx VTS module (direct, without exporter)",
 "tags": [
  "prometheus",
  "nginx",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "HTTP Host",
    "query": "label_values(nginx_vts_server_requests_total{host!=\"*\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "TOP CPU",
   "type": "graph",
   "description": "Basic cpu usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, node_load1{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\"} - node_memory_MemFree_bytes{host=~\"$host\"} - (node_memory_Cached_bytes{host=~\"$host\"} + node_memory_Buffers_bytes{host=~\"$host\"})",
     "legendFormat": "RAM Used {{host}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\"}",
     "legendFormat": "RAM Total {{host}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host=~\"$host\",device!~'rootfs|tmpfs|overlay|shm'} * 100) / node_filesystem_size_bytes{host=~\"$host\",device!~'rootfs|tmpfs|overlay|shm'})",
     "legendFormat": "{{mountpoint}}{{host}}"
    }
   ]
  },
  {
   "title": "Requests 2xx",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code!=\"total\",host=~\"$host\",code=\"2xx\"}[2m])) by (code,host)",
     "legendFormat": "{{ code }}{{ host }}"
    }
   ]
  },
  {
   "title": "Requests 5xx",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code!=\"total\",host=~\"$host\",code=\"5xx\"}[2m])) by (code,host)",
     "legendFormat": "{{ code }}{{ host }}"
    }
   ]
  },
  {
   "title": "Connections Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_main_connections{status=~\"active\"}[2m])) by (status,host)",
     "legendFormat": "{{status}} {{host}}"
    }
   ]
  },
  {
   "title": "Connections Writing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_main_connections{status=~\"writing\"}[2m])) by (status,host)",
     "legendFormat": "{{status}} {{host}}"
    }
   ]
  },
  {
   "title": "Requests 4xx",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code!=\"total\",host=~\"$host\",code=\"4xx\"}[2m])) by (code,host)",
     "legendFormat": "{{ code }}{{ host }}"
    }
   ]
  },
  {
   "title": "Connections Reading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_main_connections{status=~\"reading\"}[2m])) by (status,host)",
     "legendFormat": "{{status}} {{host}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_vts_server_request_seconds{host=~\"$host\"} > 0) by (host)",
     "legendFormat": "{{ host }} "
    }
   ]
  },
  {
   "title": "Upstream response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_vts_upstream_response_seconds{} > 3) by (upstream)",
     "legendFormat": "{{ upstream}}"
    }
   ]
  },
  {
   "title": "Requests by host",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code=\"total\", host=~\"$host\", host!=\"*\"}[5m]) > 0) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Upstream requests",
   "type": "graph",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_requests_total{code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_bytes_total{host=~\"$host\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_bytes_total{}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Cache usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nginx_vts_cache_usage_bytes{cache_size=\"max\"})) by (host)",
     "legendFormat": "max"
    },
    {
     "expr": "sum(nginx_vts_cache_usage_bytes{cache_size=\"used\"}) by (host)",
     "legendFormat": "{{ host}}"
    }
   ]
  },
  {
   "title": "Cache events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_cache_total{host=~\"$host\"}[5m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Shared memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_vts_main_shm_usage_bytes{}) by (shared)",
     "legendFormat": "{{ shared }}"
    }
   ]
  },
  {
   "title": "Cache throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_cache_bytes_total{host=~\"$host\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  }
 ]
}