{
 "title": "page-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "{\"find\":\"terms\", \"field\":\"app\", \"size\": 1000, \"orderBy\": \"doc_count\"}"
   },
   {
    "name": "uri2",
    "query": "{\"find\":\"terms\", \"field\":\"uri2\", \"size\": 100, \"query\":\"app:$app\",\"orderBy\": \"doc_count\"}"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "pv-by-app[$interval]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "app",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalPv",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "app:$app AND uri2:$uri2",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "pv-by-uri2[$interval]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "uri2",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalPv",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "app:$app AND uri2:$uri2",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "cost-by-uri2[$interval]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "uri2",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalPv",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "avgCost",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "app:$app AND uri2:$uri2 AND !(server:\"-\") AND totalCost:[1 TO 100000000]",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "pv-by-uri[$interval]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "uri",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalPv",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "app:$app AND uri2:$uri2 AND !(server:\"-\")",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "cost-by-uri[$interval]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "uri",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalPv",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "avgCost",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "app:$app AND uri2:$uri2 AND totalCost:[1 TO 100000000]",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "pv-by-server[$interval]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "serverIp",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalPv",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "app:$app",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "cost-by-server[$interval]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "serverIp",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalCost",
       "hide": true,
       "id": "1",
       "inlineScript": "_value * 1.0",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1.0" } },
       "type": "sum"
      },
      {
       "field": "avgCost",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "app:$app",
     "timeField": "stamp"
    }
   ]
  }
 ]
}