{
 "title": "postgresql-global",
 "tags": [ "postgres" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "query_result(machine_role{role=\"postgres_exporter\"} * on(host)  group_left(instance) node_load1)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "load1-$interval",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, node_load1{ host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "pg-oplog-delay",
   "type": "graph",
   "description": "扫描pg变更信息的延迟",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "measurement",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "app:pg-oplog-delay",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "QPS by db",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(irate(pg_stat_database_xact_commit{instance=~\"$host\"}[$interval]) + irate(pg_stat_database_xact_rollback{instance=~\"$host\"}[$interval])) by (datname))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "pg_locks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(pg_locks_count > 0) by (instance,datname))",
     "legendFormat": "{{instance}}/{{datname}}"
    }
   ]
  },
  {
   "title": "active connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(pg_stat_database_numbackends{instance=~\"$host\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "replication-delay-$interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, pg_stat_replication_delay)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "disk-usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, 1 - (node_filesystem_free_bytes{host=~\"$host\",mountpoint=~\"/var/lib/pgsql/.*\"} / node_filesystem_size_bytes{host=~\"$host\", mountpoint=~\"/var/lib/pgsql/.*\"}))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "pg主从状态",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "pg_stat_replication_enable", "legendFormat": "{{exported_instance}}" }
   ]
  },
  { "title": "more", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Rows-$interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_fetched{instance=~\"$host\"}[$interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_returned{instance=~\"$host\"}[$interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_inserted{instance=~\"$host\"}[$interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_updated{instance=~\"$host\"}[$interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_deleted{instance=~\"$host\"}[$interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "network traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(3, irate(node_network_receive_bytes_total{host=~\"$host\"}[$interval]))",
     "legendFormat": "recv {{device}}/{{host}}"
    },
    {
     "expr": "topk(3, irate(node_network_transmit_bytes_total{host=~\"$host\"}[$interval]))",
     "legendFormat": "trans {{device}}/{{host}}"
    }
   ]
  }
 ]
}