{
 "title": "PGBouncer",
 "description": "https://github.com/spreaker/prometheus-pgbouncer-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "project",
    "label": "项目",
    "query": "label_values(pgbouncer_up , project)"
   },
   {
    "name": "server",
    "label": "服务",
    "query": "label_values(pgbouncer_up{project=~\"$project\"}, server)"
   },
   {
    "name": "pool_id",
    "query": "label_values(pgbouncer_up{project=~\"$project\",server=~\"$server\"}, pool_id)"
   },
   {
    "name": "db",
    "label": "db",
    "query": "label_values(pgbouncer_databases_database_current_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\"},database)"
   }
  ]
 },
 "panels": [
  {
   "title": "Client active connections $db",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"})"
    }
   ]
  },
  {
   "title": "Stats queries total $db",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_queries_total{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}[5m]) ) )"
    }
   ]
  },
  {
   "title": "Database pool size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (project,server,pool_id,database) (pgbouncer_databases_database_pool_size{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Databases database reserve pool size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (project,server,pool_id,database) (pgbouncer_databases_database_reserve_pool_size{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Query Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (project,server,pool_id,database) ( rate(pgbouncer_stats_queries_duration_microseconds{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}[5m]) ) )",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Stats queries $db",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (project,server,pool_id,database) ( rate(pgbouncer_stats_queries_duration_microseconds{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}[5m]) ) )",
     "legendFormat": "{{ database }}: Stats queries duration microseconds"
    },
    {
     "expr": "sort_desc( sum by (project,server,pool_id,database) ( rate(pgbouncer_stats_waiting_duration_microseconds{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}[5m]) ) ) ",
     "legendFormat": "{{ database }}: Stats waiting duration microseconds"
    }
   ]
  },
  {
   "title": "Transactions stats $db",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (project,server,pool_id,database) ( rate(pgbouncer_stats_transactions_duration_microseconds{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}[5m]) ) )  ",
     "legendFormat": "{{ database }}: Stats transactions duration microseconds"
    },
    {
     "expr": "sort_desc( sum by (project,server,pool_id,database) ( rate(pgbouncer_stats_transactions_total{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}[5m]) ) )",
     "legendFormat": "{{ database }}: Stats transactions total"
    }
   ]
  },
  {
   "title": "Pgbouncer pools connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}",
     "legendFormat": "{{ database }}: Client active connections "
    },
    {
     "expr": "pgbouncer_pools_client_waiting_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}",
     "legendFormat": "{{ database }}: Client waiting connections"
    },
    {
     "expr": "pgbouncer_pools_server_active_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}",
     "legendFormat": "{{ database }}: Server active connections"
    },
    {
     "expr": "pgbouncer_pools_server_idle_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}",
     "legendFormat": "{{ database }}: Server idle connections"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}",
     "legendFormat": "{{ database }}: Server used connections"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}",
     "legendFormat": "{{ database }}: Server testing connections"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}",
     "legendFormat": "{{ database }}: Server login connections"
    },
    {
     "expr": "pgbouncer_databases_database_current_connections{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}",
     "legendFormat": "{{ database }}: Database current connections"
    }
   ]
  },
  {
   "title": "Total of incoming / outgoing bytes $db",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (project,server,pool_id,database) ( rate(pgbouncer_stats_received_bytes_total{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}[5m])*8 ) )",
     "legendFormat": "{{ database }}: Stats received bytes total"
    },
    {
     "expr": "sort_desc( sum by (project,server,pool_id,database) ( rate(pgbouncer_stats_sent_bytes_total{project=~\"$project\",server=~\"$server\",pool_id=~\"$pool_id\",database=~\"$db\"}[5m])*8 ) )",
     "legendFormat": "{{ database }}: Stats sent bytes total"
    }
   ]
  }
 ]
}