{
 "title": "PostgreSQL",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(pg_up{release=\"$release\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "QPS by db",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(irate(pg_stat_database_xact_commit{instance=~\"$instance\"}[$interval]) + irate(pg_stat_database_xact_rollback{instance=~\"$instance\"}[$interval])) by (datname))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(pg_stat_database_numbackends{instance=~\"$instance\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{release=\"$release\", instance=\"$instance\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{release=\"$release\", instance=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "pg_static{release=\"$release\", instance=\"$instance\"}",
       "legendFormat": "{{short_version}}"
      }
     ]
    },
    {
     "title": "Start Time",
     "type": "singlestat",
     "description": "start time of the process",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 16 },
     "format": "dateTimeFromNow",
     "valueName": "avg",
     "targets": [
      {
       "expr": "process_start_time_seconds{release=\"$release\", instance=\"$instance\"} * 1000"
      }
     ]
    },
    {
     "title": "Current fetch data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 16 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Current insert data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 16 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted{release=\"$release\", datname=~\"$datname\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Current update data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 16 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_connections{release=\"$release\", instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shared Buffers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "pg_settings_seq_page_cost" }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$instance\", mode=~\"$mode\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$instance\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}