{
 "title": "Prometheus Redis",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(redis_instance_info,instance)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(redis_used_cpu_sys{instance=\"$instance\"}[1m]) * 100) + sum(rate(redis_used_cpu_user{instance=\"$instance\"}[1m]) * 100)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current  OPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_instantaneous_ops_per_sec{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Slow log count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_slowlog_length{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory_used_peak（M）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_memory_used_peak_bytes{instance=\"$instance\"} / 1024 / 1024",
     "legendFormat": "memory_used_peak"
    }
   ]
  },
  {
   "title": "Current Role",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_connected_slaves{instance=\"$instance\"}",
     "legendFormat": "connected_slaves"
    }
   ]
  },
  {
   "title": "Maxmemory ( M )",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_config_maxmemory{instance=\"$instance\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "memory_used ( M )",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"$instance\"} / 1024 / 1024 "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\"}  / redis_config_maxmemory{instance=~\"$instance\"} )"
    }
   ]
  },
  {
   "title": "memory_fragmentation_ratio",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_memory_fragmentation_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "keyspace_hit_ratio",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "( sum(rate(redis_keyspace_hits_total{instance=\"$instance\"}[1m])) ) / ( sum(rate(redis_keyspace_misses_total{instance=\"$instance\"}[1m])) + sum(rate(redis_keyspace_hits_total{instance=\"$instance\"}[1m]))) * 100",
     "legendFormat": "keyspace_hit_ratio"
    }
   ]
  },
  {
   "title": "pubsub channels",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_pubsub_channels{instance=\"$instance\"}",
     "legendFormat": "pubsub_channels"
    }
   ]
  },
  {
   "title": "AOF_enabled",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_aof_enabled{instance=\"$instance\"}",
     "legendFormat": "redis_aof_enabled"
    }
   ]
  },
  {
   "title": "rejected_connections_total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(redis_rejected_connections_total{instance=\"$instance\"}[1m])",
     "legendFormat": "rejected_connections_total"
    }
   ]
  },
  {
   "title": "OPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_instantaneous_ops_per_sec{instance=\"$instance\"}",
     "legendFormat": "instantaneous_ops_per_sec"
    }
   ]
  },
  {
   "title": " command_call_duration_seconds_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15,irate(redis_command_call_duration_seconds_count{instance=\"$instance\"}[1m]) > 10 )",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "command_call_duration_seconds_sum ( s )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(redis_command_call_duration_seconds_sum{instance=\"$instance\"}[1m]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "connected Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}",
     "legendFormat": "connected clients"
    }
   ]
  },
  {
   "title": "memory_used ( G )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"$instance\"} / 1024 / 1024 / 1024 ",
     "legendFormat": "memory_used"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"} ",
     "legendFormat": "memory used"
    },
    {
     "expr": "redis_memory_used_rss_bytes{instance=~\"$instance\"} ",
     "legendFormat": "rss used"
    },
    {
     "expr": "redis_memory_used_peak_bytes{instance=~\"$instance\"} ",
     "legendFormat": "peak used"
    }
   ]
  },
  {
   "title": "CPU Utilization ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_used_cpu_sys{instance=\"$instance\"}[1m]) * 100",
     "legendFormat": "used_cpu_sys"
    },
    {
     "expr": "rate(redis_used_cpu_user{instance=\"$instance\"}[1m]) * 100",
     "legendFormat": "used_cpu_user"
    }
   ]
  },
  {
   "title": "memory_fragmentation_ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_memory_fragmentation_ratio{instance=\"$instance\"}",
     "legendFormat": "memory_fragmentation_ratio"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(redis_net_input_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "irate(redis_net_output_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=\"$instance\"}[1m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=\"$instance\"}[1m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "instantaneous_input | output  ( kbps ) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_instantaneous_input_kbps{instance=\"$instance\"}",
     "legendFormat": " instantaneous_input_kbps"
    },
    {
     "expr": "redis_instantaneous_output_kbps{instance=\"$instance\"}",
     "legendFormat": "instantaneous_output_kbps"
    }
   ]
  },
  {
   "title": "Client biggest input buf  output list and blocked clients | rejected connections total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_client_biggest_input_buf{instance=\"$instance\"}",
     "legendFormat": "Client_biggest_input_buf"
    },
    {
     "expr": "redis_client_longest_output_list{instance=\"$instance\"}",
     "legendFormat": "Client_longest_output_list"
    },
    {
     "expr": "redis_blocked_clients{instance=\"$instance\"}",
     "legendFormat": " blocked_clients"
    },
    {
     "expr": "redis_rejected_connections_total{instance=\"$instance\"}",
     "legendFormat": "rejected_connections_total"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "rdb info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_bgsave_in_progress{instance=\"$instance\"}",
     "legendFormat": "rdb_bgsave_in_progress"
    },
    {
     "expr": "rate(redis_rdb_changes_since_last_save{instance=\"$instance\"}[1m])",
     "legendFormat": "rdb_changes_since_last_save"
    },
    {
     "expr": "redis_rdb_current_bgsave_duration_sec{instance=\"$instance\"}",
     "legendFormat": "rdb_current_bgsave_duration_sec"
    },
    {
     "expr": "redis_rdb_last_bgsave_status{instance=\"$instance\"}",
     "legendFormat": "rdb_last_bgsave_status"
    },
    {
     "expr": "redis_latest_fork_usec{instance=\"$instance\"} / 1000",
     "legendFormat": "redis_latest_fork_usec"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_expired_keys_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "expired"
    },
    {
     "expr": "irate(redis_evicted_keys_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "redis_aof_current_rewrite_duration_sec and last_bgrewrite_status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_aof_current_rewrite_duration_sec{instance=\"$instance\"}[1m])",
     "legendFormat": "AOF current rewrite duration_sec"
    },
    {
     "expr": "redis_aof_last_bgrewrite_status{instance=\"$instance\"}",
     "legendFormat": "aof_last_bgrewrite_status"
    },
    {
     "expr": "redis_aof_last_write_status{instance=\"$instance\"}",
     "legendFormat": "aof_last_write_status"
    },
    {
     "expr": "redis_aof_rewrite_in_progress{instance=\"$instance\"}",
     "legendFormat": "aof_rewrite_in_progress"
    }
   ]
  },
  {
   "title": "db_keys_expiring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_db_keys_expiring{instance=\"$instance\"}[1m])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "redis_master_link_up (only slave)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_master_link_up{instance=\"$instance\"}",
     "legendFormat": "master_link_up"
    }
   ]
  },
  {
   "title": "master_last_io_seconds ( slave only )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_master_last_io_seconds{instance=\"$instance\"}",
     "legendFormat": "master_last_io_seconds"
    }
   ]
  }
 ]
}