{
 "title": "RocketMQ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "query_result(machine_role{role=\"rocketmq\"} * on(host)  group_left(instance) node_load1)"
   }
  ]
 },
 "panels": [
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOP CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, node_load1{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\"} - node_memory_MemFree_bytes{host=~\"$host\"} - (node_memory_Cached_bytes{host=~\"$host\"} + node_memory_Buffers_bytes{host=~\"$host\"})",
     "legendFormat": "RAM Used {{host}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\"}",
     "legendFormat": "RAM Total {{host}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host=~\"$host\",device!~'rootfs|tmpfs|overlay|shm'} * 100) / node_filesystem_size_bytes{host=~\"$host\",device!~'rootfs|tmpfs|overlay|shm'})",
     "legendFormat": "{{mountpoint}}{{host}}"
    }
   ]
  },
  {
   "title": "broker tps & broker qps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_broker_tps", "legendFormat": "{{brokerIP}}" },
    { "expr": "rocketmq_broker_qps", "legendFormat": "{{brokerIP}}" }
   ]
  },
  {
   "title": "rocketmq_consumer_tps",
   "type": "graph",
   "description": "消费tps",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,(rocketmq_consumer_tps > 10))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "rocketmq_producer_tps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,rocketmq_producer_tps>10)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "rocketmq_message_accumulation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Hide",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "runtime tps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rocketmq_brokeruntime_gettotal_tps10>0)"
      }
     ]
    },
    {
     "title": "rocketmq_consumer_offset",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,rocketmq_consumer_offset >500)"
      }
     ]
    },
    {
     "title": "topk(5,rocketmq_group_get_latency_by_storetime>0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rocketmq_group_get_latency_by_storetime>0)"
      }
     ]
    },
    {
     "title": "broker runtime info",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rocketmq_brokeruntime_msg_put_total_today_now>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_msg_gettotal_today_now>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_dispatch_behind_bytes>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_put_message_size_total>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_put_message_average_size>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_msg_gettotal_yesterdaymorning>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_msg_puttotal_yesterdaymorning>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_msg_gettotal_todaymorning>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_msg_puttotal_todaymorning>0)"
      }
     ]
    },
    {
     "title": "disk space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rocketmq_brokeruntime_commitlog_disk_ratio>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_consumequeue_disk_ratio>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_commitlogdir_capacity_free>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_commitlogdir_capacity_total>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_commitlog_maxoffset>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_commitlog_minoffset>0)"
      }
     ]
    },
    {
     "title": "threadpoolqueue_headwait_timemills",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rocketmq_brokeruntime_pull_threadpoolqueue_headwait_timemills>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_query_threadpoolqueue_headwait_timemills>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_send_threadpoolqueue_headwait_timemills>0)"
      }
     ]
    },
    {
     "title": "rocketmq_consumer_message_size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,rocketmq_consumer_message_size >0 )"
      }
     ]
    },
    {
     "title": "PutMessageDistributeTime",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_0ms>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_0to10ms>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_10to50ms>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_50to100ms>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_100to200ms>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_200to500ms>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_500to1s>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_1to2s>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_2to3s>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_3to4s>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_4to5s>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_5to10s>0)"
      },
      {
       "expr": "topk(5,rocketmq_brokeruntime_pmdt_10stomore>0)"
      }
     ]
    },
    {
     "title": "consume client info",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rocketmq_client_consume_ok_msg_tps>0)"
      }
     ]
    },
    {
     "title": "rocketmq_producer_offset",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rocketmq_producer_offset>0)"
      }
     ]
    },
    {
     "title": "rocketmq_producer_message_size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,rocketmq_producer_message_size > 0)"
      }
     ]
    }
   ]
  }
 ]
}