{
 "title": "service-dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "{\"find\":\"terms\", \"field\":\"app\", \"size\": 1000}"
   },
   {
    "name": "method",
    "query": "{\"find\":\"terms\", \"field\":\"method\", \"size\": 1000, \"query\":\"app:$app\"}"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "service-by-app[$interval]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "app",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "app:$app AND method:$method AND !(module:FAP)",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "service-by-caller[$interval]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "caller",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "app:$app AND method:$method AND !(module:FAP) AND totalCost:[1 TO 100000000]",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "service-by-module[$interval]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "module",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "app:$app AND method:$method AND !(module:FAP)",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "cost-by-module[$interval]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "module",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalCount",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "totalCost",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "5",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "4" },
        { "name": "var2", "pipelineAgg": "1" }
       ],
       "settings": {
        "script": "params.var1 * 1.0 / params.var2"
       },
       "type": "bucket_script"
      }
     ],
     "query": "app:$app AND method:$method AND !(module:FAP) AND totalCost:[1 TO 100000000]",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "service-by-method[$interval]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "method",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "app:$app AND method:$method AND !(module:FAP)",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "cost-by-method[$interval]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "method",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "totalCount",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "totalCost",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "5",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "4" },
        { "name": "var2", "pipelineAgg": "1" }
       ],
       "settings": {
        "script": "params.var1 * 1.0 / params.var2"
       },
       "type": "bucket_script"
      }
     ],
     "query": "app:$app AND method:$method AND !(module:FAP)  AND totalCost:[1 TO 100000000]",
     "timeField": "stamp"
    }
   ]
  }
 ]
}