{
 "title": "trace-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "trace-by-app",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "app",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "trace-by-ea",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ea",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "stamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "trace-by-request",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "iface",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "6", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "method",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "6", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "url",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "6", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      {
       "field": "cost",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "trace-by-trace-id",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "traceId",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "trace-by-uid",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "uid",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "log-cep",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "stamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "app:fs-cep-provider AND iface:CEP",
     "timeField": "stamp"
    }
   ]
  },
  {
   "title": "trace-detail",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "stamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "stamp"
    }
   ]
  }
 ]
}