{
 "title": "虚机资源概览",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "cpu使用率百分比top 10",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(increase(node_cpu_seconds_total{mode!=\"idle\"}[2m])) by(instance) / sum(increase(node_cpu_seconds_total{}[2m]) ) by(instance) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "剩余可用内存bottom 10",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(10,node_memory_MemAvailable_bytes{})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘使用率top10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,100 - ((node_filesystem_avail_bytes{device!~'rootfs|tmpfs|overlay|shm'} * 100) / (node_filesystem_size_bytes{device!~'rootfs|tmpfs|overlay|shm'}- (node_filesystem_free_bytes{device!~'rootfs|tmpfs|overlay|shm'}-node_filesystem_avail_bytes{device!~'rootfs|tmpfs|overlay|shm'})) ) )",
     "legendFormat": "{{instance}}{{mountpoint}}"
    }
   ]
  },
  {
   "title": "hidden",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "磁盘使用率",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs|tmpfs|overlay|shm'} * 100) / (node_filesystem_size_bytes{device!~'rootfs|tmpfs|overlay|shm'}- (node_filesystem_free_bytes{device!~'rootfs|tmpfs|overlay|shm'}-node_filesystem_avail_bytes{device!~'rootfs|tmpfs|overlay|shm'})) ) "
      },
      {
       "expr": "node_filesystem_avail_bytes{device!~'rootfs|tmpfs|overlay|shm'}"
      }
     ]
    }
   ]
  }
 ]
}