{
 "title": "ZooKeeper",
 "description": "ZooKeeper Dashboard for Prometheus metrics scraper",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "query_result(machine_role{role=\"zookeeper\"} * on(host)  group_right node_load1)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOP CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, node_load1{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\"} - node_memory_MemFree_bytes{host=~\"$host\"} - (node_memory_Cached_bytes{host=~\"$host\"} + node_memory_Buffers_bytes{host=~\"$host\"})",
     "legendFormat": "RAM Used {{host}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\"}",
     "legendFormat": "RAM Total {{host}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host=~\"$host\",device!~'rootfs|tmpfs|overlay|shm'} * 100) / node_filesystem_size_bytes{host=~\"$host\",device!~'rootfs|tmpfs|overlay|shm'})",
     "legendFormat": "{{mountpoint}}{{host}}"
    }
   ]
  },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "znode_count", "legendFormat": "{{instance}} znode_count" }
   ]
  },
  {
   "title": "ephemerals_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ephemerals_count", "legendFormat": "{{instance}} ephemerals_count" }
   ]
  },
  {
   "title": "global_sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "global_sessions", "legendFormat": "global_sessions" }
   ]
  },
  {
   "title": "write_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,write_per_namespace>0)",
     "legendFormat": "{{instance}} write_per_namespace:{{key}}-{{quantile}}"
    },
    {
     "expr": "topk(10,write_per_namespace_count>0)",
     "legendFormat": "{{instance}} write_per_namespace_count:{{key}}"
    },
    {
     "expr": "topk(10,write_per_namespace_sum>0)",
     "legendFormat": "{{instance}} write_per_namespace_sum:{{key}}"
    }
   ]
  },
  {
   "title": "read_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,read_per_namespace>0)",
     "legendFormat": "{{instance}} read_per_namespace:{{key}}-{{quantile}}"
    },
    {
     "expr": "topk(10,read_per_namespace_count>0)",
     "legendFormat": "{{instance}} read_per_namespace_count:{{key}}"
    },
    {
     "expr": "topk(10,read_per_namespace_sum>0)",
     "legendFormat": "{{instance}} read_per_namespace_sum:{{key}}"
    }
   ]
  },
  {
   "title": "local_sessions ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "local_sessions", "legendFormat": "local_sessions " }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "packets_sent", "legendFormat": "{{instance}} packets_sent" }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "packets_received", "legendFormat": "{{instance}} packets_received" }
   ]
  },
  {
   "title": "response_packet_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "response_packet_cache_misses",
     "legendFormat": "{{instance}} response_packet_cache_misses"
    },
    {
     "expr": "response_packet_cache_hits",
     "legendFormat": "{{instance}} response_packet_cache_hits"
    }
   ]
  },
  {
   "title": "bytes_received_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bytes_received_count",
     "legendFormat": "{{instance}} bytes_received_count"
    }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "approximate_data_size",
     "legendFormat": "{{instance}} approximate_data_size"
    }
   ]
  },
  {
   "title": "outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_requests",
     "legendFormat": "{{instance}} outstanding_requests"
    }
   ]
  },
  {
   "title": "unrecoverable_error_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unrecoverable_error_count",
     "legendFormat": "{{instance}} unrecoverable_error_count"
    }
   ]
  },
  {
   "title": "ensemble_auth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ensemble_auth_fail",
     "legendFormat": "{{instance}} ensemble_auth_fail"
    },
    {
     "expr": "ensemble_auth_success",
     "legendFormat": "{{instance}} ensemble_auth_success"
    },
    {
     "expr": "ensemble_auth_skip",
     "legendFormat": "{{instance}} ensemble_auth_skip"
    }
   ]
  },
  {
   "title": "startup_txns_loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "startup_txns_loaded",
     "legendFormat": "{{instance}} startup_txns_loaded-{{quantile}}"
    },
    {
     "expr": "startup_txns_loaded_count",
     "legendFormat": "{{instance}} startup_txns_loaded_count"
    },
    {
     "expr": "startup_txns_loaded_sum",
     "legendFormat": "{{instance}} startup_txns_loaded_sum"
    }
   ]
  },
  {
   "title": "startup_snap_load_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "startup_snap_load_time",
     "legendFormat": "{{instance}} startup_snap_load_time-{{quantile}}"
    },
    {
     "expr": "startup_snap_load_time_count",
     "legendFormat": "{{instance}} startup_snap_load_time_count"
    },
    {
     "expr": "startup_snap_load_time_sum",
     "legendFormat": "{{instance}} startup_snap_load_time_sum"
    }
   ]
  },
  {
   "title": "dbinittime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbinittime",
     "legendFormat": "{{instance}} dbinittime-{{quantile}}"
    },
    { "expr": "dbinittime_count", "legendFormat": "{{instance}} dbinittime_count" },
    { "expr": "dbinittime_sum", "legendFormat": "{{instance}} dbinittime_sum" }
   ]
  },
  {
   "title": "Client/Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "client_response_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "last_client_response_size",
       "legendFormat": "{{instance}} last_client_response_size"
      },
      {
       "expr": "min_client_response_size",
       "legendFormat": "{{instance}} min_client_response_size"
      },
      {
       "expr": "max_client_response_size",
       "legendFormat": "{{instance}} max_client_response_size"
      }
     ]
    },
    {
     "title": "connection_request_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_request_count",
       "legendFormat": "{{instance}} connection_request_count"
      }
     ]
    },
    {
     "title": "connection_rejected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_rejected",
       "legendFormat": "{{instance}} connection_rejected"
      }
     ]
    },
    {
     "title": "connection_drop_probability",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_drop_probability",
       "legendFormat": "{{instance}} connection_drop_probability"
      }
     ]
    },
    {
     "title": "connection_drop_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_drop_count",
       "legendFormat": "{{instance}} connection_drop_count"
      }
     ]
    },
    {
     "title": "connection_token_deficit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "connection_token_deficit",
       "legendFormat": "{{instance}} connection_token_deficit-{{quantile}}"
      },
      {
       "expr": "connection_token_deficit_count",
       "legendFormat": "{{instance}} connection_token_deficit_count"
      },
      {
       "expr": "connection_token_deficit_sum",
       "legendFormat": "{{instance}} connection_token_deficit_sum"
      }
     ]
    },
    {
     "title": "num_alive_connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "num_alive_connections",
       "legendFormat": "{{instance}} num_alive_connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Quorum/Leader Election",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "quorum_size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "targets": [
      { "expr": "quorum_size", "legendFormat": "quorum_size" }
     ]
    },
    {
     "title": "learner/observer",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "targets": [
      { "expr": "learners", "legendFormat": "learners" },
      { "expr": "synced_non_voting_followers", "legendFormat": "synced_non_voting_followers" },
      { "expr": "synced_observers", "legendFormat": "synced_observers" }
     ]
    },
    {
     "title": "election_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "election_time", "legendFormat": "{{instance}} election_time" },
      {
       "expr": "election_time_count",
       "legendFormat": "{{instance}} election_time_count"
      },
      { "expr": "election_time_sum", "legendFormat": "{{instance}} election_time_sum" },
      {
       "expr": "election_time_sum/election_time_count",
       "legendFormat": "{{instance}} election_avg_time"
      }
     ]
    },
    {
     "title": "leader_uptime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "leader_uptime", "legendFormat": "{{instance}} leader_uptime" },
      { "expr": "uptime", "legendFormat": "{{instance}} uptime" }
     ]
    },
    {
     "title": "local_write_committed_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "local_write_committed_time_ms",
       "legendFormat": "{{instance}} local_write_committed_time_ms-{{quantile}}"
      },
      {
       "expr": "local_write_committed_time_ms_count",
       "legendFormat": "{{instance}} local_write_committed_time_ms_count"
      },
      {
       "expr": "local_write_committed_time_ms_sum",
       "legendFormat": "{{instance}} local_write_committed_time_ms_sum"
      }
     ]
    },
    {
     "title": "server_write_committed_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "server_write_committed_time_ms",
       "legendFormat": "{{instance}} server_write_committed_time_ms-{{quantile}}"
      }
     ]
    },
    {
     "title": "learner_commit_received_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "learner_commit_received_count",
       "legendFormat": "{{instance}} learner_commit_received_count"
      }
     ]
    },
    {
     "title": "proposal_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "proposal_count", "legendFormat": "{{instance}} proposal_count" }
     ]
    },
    {
     "title": "diff_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "diff_count", "legendFormat": "{{instance}} diff_count" }
     ]
    },
    {
     "title": "commit_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "commit_count", "legendFormat": "{{instance}} commit_count" }
     ]
    },
    {
     "title": "quit_leading_due_to_disloyal_voter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quit_leading_due_to_disloyal_voter",
       "legendFormat": "{{instance}} quit_leading_due_to_disloyal_voter"
      }
     ]
    },
    {
     "title": "looking_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "looking_count", "legendFormat": "{{instance}} looking_count" }
     ]
    },
    {
     "title": "follower_sync_time_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "follower_sync_time",
       "legendFormat": "{{instance}} follower_sync_time-{{quantile}}"
      },
      {
       "expr": "follower_sync_time_count",
       "legendFormat": "{{instance}} follower_sync_time_count"
      },
      {
       "expr": "follower_sync_time_sum",
       "legendFormat": "{{instance}} follower_sync_time_sum"
      }
     ]
    },
    {
     "title": "proposal_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "last_proposal_size",
       "legendFormat": "{{instance}} last_proposal_size"
      },
      { "expr": "max_proposal_size", "legendFormat": "{{instance}} max_proposal_size" },
      { "expr": "min_proposal_size", "legendFormat": "{{instance}} min_proposal_size" }
     ]
    },
    {
     "title": "learner_handler_qp_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "learner_handler_qp_size",
       "legendFormat": "{{instance}} learner_handler_qp_size:{{key}}-{{quantile}}"
      },
      {
       "expr": "learner_handler_qp_size_count",
       "legendFormat": "{{instance}} learner_handler_qp_size_count:{{key}}"
      },
      {
       "expr": "learner_handler_qp_size_count",
       "legendFormat": "{{instance}} learner_handler_qp_size_sum:{{key}}"
      }
     ]
    }
   ]
  },
  {
   "title": "session/watch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "close_session_prep_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "close_session_prep_time",
       "legendFormat": "{{instance}} close_session_prep_time"
      }
     ]
    },
    {
     "title": "pending_session_queue_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pending_session_queue_size",
       "legendFormat": "{{instance}} pending_session_queue_size_count-{{quantile}}"
      },
      {
       "expr": "pending_session_queue_size_count",
       "legendFormat": "{{instance}} pending_session_queue_size_count"
      },
      {
       "expr": "pending_session_queue_size_sum",
       "legendFormat": "{{instance}} pending_session_queue_size_sum"
      }
     ]
    },
    {
     "title": "reads_after_write_in_session_queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "reads_after_write_in_session_queue_count",
       "legendFormat": "{{instance}} reads_after_write_in_session_queue_count"
      },
      {
       "expr": "reads_after_write_in_session_queue_sum",
       "legendFormat": "{{instance}} reads_after_write_in_session_queue_sum"
      },
      {
       "expr": "reads_after_write_in_session_queue",
       "legendFormat": "{{instance}} reads_after_write_in_session_queue-{{quantile}}"
      }
     ]
    },
    {
     "title": "reads_issued_from_session_queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "reads_issued_from_session_queue",
       "legendFormat": "{{instance}} reads_issued_from_session_queue-{{quantile}}"
      },
      {
       "expr": "reads_issued_from_session_queue_count",
       "legendFormat": "{{instance}} reads_issued_from_session_queue_count"
      },
      {
       "expr": "reads_issued_from_session_queue_sum",
       "legendFormat": "{{instance}} reads_issued_from_session_queue_sum"
      }
     ]
    },
    {
     "title": "requests_in_session_queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "requests_in_session_queue",
       "legendFormat": "{{instance}} requests_in_session_queue-{{quantile}}"
      },
      {
       "expr": "requests_in_session_queue_count",
       "legendFormat": "{{instance}} requests_in_session_queue_count"
      },
      {
       "expr": "requests_in_session_queue_sum",
       "legendFormat": "{{instance}} requests_in_session_queue_sum"
      }
     ]
    },
    {
     "title": "session_queues_drained",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "session_queues_drained",
       "legendFormat": "{{instance}} session_queues_drained-{{quantile}}"
      },
      {
       "expr": "session_queues_drained_count",
       "legendFormat": "{{instance}} session_queues_drained_count"
      },
      {
       "expr": "session_queues_drained_sum",
       "legendFormat": "{{instance}} session_queues_drained_sum"
      }
     ]
    },
    {
     "title": "stale_sessions_expired",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "stale_sessions_expired",
       "legendFormat": "{{instance}} stale_sessions_expired"
      }
     ]
    },
    {
     "title": "revalidate_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "revalidate_count", "legendFormat": "{{instance}} revalidate_count" }
     ]
    },
    {
     "title": "reads_issued_from_session_queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "reads_issued_from_session_queue",
       "legendFormat": "{{instance}} reads_issued_from_session_queue"
      },
      {
       "expr": "reads_issued_from_session_queue_count",
       "legendFormat": "{{instance}} reads_issued_from_session_queue_count"
      },
      {
       "expr": "reads_issued_from_session_queue_sum",
       "legendFormat": "{{instance}} reads_issued_from_session_queue_sum"
      }
     ]
    },
    {
     "title": "add_dead_watcher_stall_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "add_dead_watcher_stall_time",
       "legendFormat": "{{instance}} add_dead_watcher_stall_time"
      }
     ]
    },
    {
     "title": "sessionless_connections_expired",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sessionless_connections_expired",
       "legendFormat": "{{instance}} sessionless_connections_expired"
      }
     ]
    },
    {
     "title": "watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "watch_count", "legendFormat": "{{instance}} watch_count" }
     ]
    },
    {
     "title": "node_children_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_children_watch_count",
       "legendFormat": "{{instance}} node_children_watch_count-{{quantile}}"
      },
      {
       "expr": "node_children_watch_count_count",
       "legendFormat": "{{instance}} node_children_watch_count_count"
      },
      {
       "expr": "node_children_watch_count_sum",
       "legendFormat": "{{instance}} node_children_watch_count_sum"
      }
     ]
    },
    {
     "title": "node_changed_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_changed_watch_count",
       "legendFormat": "{{instance}} node_changed_watch_count-{{quantile}}"
      },
      {
       "expr": "node_changed_watch_count_count",
       "legendFormat": "{{instance}} node_changed_watch_count_count"
      },
      {
       "expr": "node_changed_watch_count_sum",
       "legendFormat": "{{instance}} node_changed_watch_count_sum"
      }
     ]
    },
    {
     "title": "node_deleted_watch_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_deleted_watch_count",
       "legendFormat": "{{instance}} node_deleted_watch_count-{{quantile}}"
      },
      {
       "expr": "node_deleted_watch_count_count",
       "legendFormat": "{{instance}} node_deleted_watch_count_count"
      },
      {
       "expr": "node_deleted_watch_count_sum",
       "legendFormat": "{{instance}} node_deleted_watch_count_sum"
      }
     ]
    },
    {
     "title": "dead_watchers_cleared",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dead_watchers_cleared",
       "legendFormat": "{{instance}} dead_watchers_cleared"
      }
     ]
    }
   ]
  },
  {
   "title": "disk/snapshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "file_descriptor",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "targets": [
      { "expr": "open_file_descriptor_count", "legendFormat": "open_file_descriptor_count" },
      { "expr": "process_max_fds", "legendFormat": "process_max_fds" }
     ]
    },
    {
     "title": "snapshottime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "snapshottime", "legendFormat": "{{instance}} snapshottime" },
      {
       "expr": "snapshottime_count",
       "legendFormat": "{{instance}} snapshottime_count"
      },
      { "expr": "snapshottime_sum", "legendFormat": "{{instance}} snapshottime_sum" }
     ]
    },
    {
     "title": "fsynctime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "fsynctime", "legendFormat": "{{instance}} fsynctime" },
      { "expr": "fsynctime_count", "legendFormat": "{{instance}} fsynctime_count" },
      { "expr": "fsynctime_sum", "legendFormat": "{{instance}} fsynctime_sum" }
     ]
    },
    {
     "title": "snap_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "snap_count", "legendFormat": "{{instance}} snap_count" }
     ]
    }
   ]
  },
  {
   "title": "prep_processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "prep_processor_queue_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prep_processor_queue_time_ms",
       "legendFormat": "{{instance}} prep_processor_queue_time_ms-{{quantile}}"
      },
      {
       "expr": "prep_processor_queue_time_ms_count",
       "legendFormat": "{{instance}} prep_processor_queue_time_ms_count"
      },
      {
       "expr": "prep_processor_queue_time_ms_sum",
       "legendFormat": "{{instance}} prep_processor_queue_time_ms_sum"
      }
     ]
    },
    {
     "title": "outstanding_changes_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "outstanding_changes_queued",
       "legendFormat": "{{instance}} outstanding_changes_queued"
      },
      {
       "expr": "outstanding_changes_removed",
       "legendFormat": "{{instance}} outstanding_changes_removed"
      }
     ]
    },
    {
     "title": "prep_processor_queue_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prep_processor_queue_size",
       "legendFormat": "{{instance}} prep_processor_queue_size-{{quantile}}"
      },
      {
       "expr": "prep_processor_queue_size_count",
       "legendFormat": "{{instance}} prep_processor_queue_size_count"
      },
      {
       "expr": "prep_processor_queue_size_sum",
       "legendFormat": "{{instance}} prep_processor_queue_size_sum"
      }
     ]
    },
    {
     "title": "prep_processor_request_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prep_processor_request_queued",
       "legendFormat": "{{instance}} prep_processor_request_queued"
      }
     ]
    },
    {
     "title": "prep_process_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "prep_process_time", "legendFormat": "{{instance}} prep_process_time" }
     ]
    }
   ]
  },
  {
   "title": "sync_processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "sync_processor_request_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sync_processor_request_queued",
       "legendFormat": "{{instance}} sync_processor_request_queued"
      }
     ]
    },
    {
     "title": "sync_processor_batch_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sync_processor_batch_size",
       "legendFormat": "{{instance}} sync_processor_batch_size-{{quantile}}"
      },
      {
       "expr": "sync_processor_batch_size_count",
       "legendFormat": "{{instance}} sync_processor_batch_size_count"
      },
      {
       "expr": "sync_processor_batch_size_sum",
       "legendFormat": "{{instance}} sync_processor_batch_size_sum"
      }
     ]
    },
    {
     "title": "sync_processor_queue_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sync_processor_queue_size",
       "legendFormat": "{{instance}} sync_processor_queue_size-{{quantile}}"
      },
      {
       "expr": "sync_processor_queue_size_count",
       "legendFormat": "{{instance}} sync_processor_queue_size_count"
      },
      {
       "expr": "sync_processor_queue_size_sum",
       "legendFormat": "{{instance}} sync_processor_queue_size_sum"
      }
     ]
    },
    {
     "title": "sync_processor_queue_flush_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sync_processor_queue_flush_time_ms",
       "legendFormat": "{{instance}} sync_processor_queue_flush_time_ms-{{quantile}}"
      }
     ]
    },
    {
     "title": "sync_process_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sync_process_time",
       "legendFormat": "{{instance}} sync_process_time-{{quantile}}"
      },
      {
       "expr": "sync_process_time_count",
       "legendFormat": "{{instance}} sync_process_time_count"
      },
      {
       "expr": "sync_process_time",
       "legendFormat": "{{instance}} sync_process_time_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "commit_processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "write_batch_time_in_commit_processor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "write_batch_time_in_commit_processor",
       "legendFormat": "{{instance}} write_batch_time_in_commit_processor-{{quantile}}"
      },
      {
       "expr": "write_batch_time_in_commit_processor_count",
       "legendFormat": "{{instance}} write_batch_time_in_commit_processor_count"
      },
      {
       "expr": "write_batch_time_in_commit_processor_sum",
       "legendFormat": "{{instance}} write_batch_time_in_commit_processor_sum"
      }
     ]
    },
    {
     "title": "write_batch_time_in_commit_processor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "write_batch_time_in_commit_processor",
       "legendFormat": "{{instance}} -write_batch_time_in_commit_processor{{quantile}}"
      },
      {
       "expr": "write_batch_time_in_commit_processor_count",
       "legendFormat": "{{instance}} write_batch_time_in_commit_processor_count"
      },
      {
       "expr": "write_batch_time_in_commit_processor_sum",
       "legendFormat": "{{instance}} write_batch_time_in_commit_processor_sum"
      }
     ]
    },
    {
     "title": "commit_process_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "commit_process_time",
       "legendFormat": "{{instance}} commit_process_time-{{quantile}}"
      },
      {
       "expr": "commit_process_time_count",
       "legendFormat": "{{instance}} commit_process_time_count"
      },
      {
       "expr": "commit_process_time_sum",
       "legendFormat": "{{instance}} commit_process_time_sum"
      }
     ]
    },
    {
     "title": "read_commit_proc_issued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "read_commit_proc_issued",
       "legendFormat": "{{instance}} read_commit_proc_issued-{{quantile}}"
      },
      {
       "expr": "read_commit_proc_issued_count",
       "legendFormat": "{{instance}} read_commit_proc_issued_count"
      },
      {
       "expr": "read_commit_proc_issued_sum",
       "legendFormat": "{{instance}} read_commit_proc_issued_sum"
      }
     ]
    },
    {
     "title": "read_commitproc_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "read_commitproc_time_ms",
       "legendFormat": "{{instance}} read_commitproc_time_ms-{{quantile}}"
      },
      {
       "expr": "read_commitproc_time_ms_count",
       "legendFormat": "{{instance}} read_commitproc_time_ms_count"
      },
      {
       "expr": "read_commitproc_time_ms_sum",
       "legendFormat": "{{instance}} read_commitproc_time_ms_sum"
      }
     ]
    },
    {
     "title": "request_commit_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "request_commit_queued",
       "legendFormat": "{{instance}} request_commit_queued"
      }
     ]
    },
    {
     "title": "write_commitproc_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "write_commitproc_time_ms",
       "legendFormat": "{{instance}} write_commitproc_time_ms-{{quantile}}"
      },
      {
       "expr": "write_commitproc_time_ms_count",
       "legendFormat": "{{instance}} write_commitproc_time_ms_count"
      },
      {
       "expr": "write_commitproc_time_ms_sum",
       "legendFormat": "{{instance}} write_commitproc_time_ms_sum"
      }
     ]
    },
    {
     "title": "write_commit_proc_req_queued",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "write_commit_proc_req_queued",
       "legendFormat": "{{instance}} write_commit_proc_req_queued-{{quantile}}"
      },
      {
       "expr": "write_commit_proc_req_queued_count",
       "legendFormat": "{{instance}} write_commit_proc_req_queued_count"
      },
      {
       "expr": "write_commit_proc_req_queued_sum",
       "legendFormat": "{{instance}} write_commit_proc_req_queued_sum"
      }
     ]
    },
    {
     "title": "concurrent_request_processing_in_commit_processor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "concurrent_request_processing_in_commit_processor",
       "legendFormat": "{{instance}}concurrent_request_processing_in_commit_processor-{{quantile}}"
      },
      {
       "expr": "concurrent_request_processing_in_commit_processor_count",
       "legendFormat": "{{instance}} concurrent_request_processing_in_commit_processor_count"
      },
      {
       "expr": "concurrent_request_processing_in_commit_processor_sum",
       "legendFormat": "{{instance}} concurrent_request_processing_in_commit_processor_sum"
      }
     ]
    },
    {
     "title": "time_waiting_empty_pool_in_commit_processor_read_ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "time_waiting_empty_pool_in_commit_processor_read_ms",
       "legendFormat": "{{instance}} time_waiting_empty_pool_in_commit_processor_read_ms-{{quantile}}"
      },
      {
       "expr": "time_waiting_empty_pool_in_commit_processor_read_ms_count",
       "legendFormat": "{{instance}} time_waiting_empty_pool_in_commit_processor_read_ms_count"
      },
      {
       "expr": "time_waiting_empty_pool_in_commit_processor_read_ms_sum",
       "legendFormat": "{{instance}} time_waiting_empty_pool_in_commit_processor_read_ms_sum"
      }
     ]
    },
    {
     "title": "om_commit_process_time_ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "om_commit_process_time_ms",
       "legendFormat": "{{instance}} om_commit_process_time_ms-{{quantile}}"
      },
      {
       "expr": "om_commit_process_time_ms_count",
       "legendFormat": "{{instance}} om_commit_process_time_ms_count"
      },
      {
       "expr": "om_commit_process_time_ms_sum",
       "legendFormat": "{{instance}} om_commit_process_time_ms_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "final_processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "write_final_proc_time_ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "write_final_proc_time_ms",
       "legendFormat": "{{instance}} write_final_proc_time_ms-{{quantile}}"
      },
      {
       "expr": "write_final_proc_time_ms_count",
       "legendFormat": "{{instance}} write_final_proc_time_ms_count"
      },
      {
       "expr": "write_final_proc_time_ms_sum",
       "legendFormat": "{{instance}} write_final_proc_time_ms_sum"
      }
     ]
    },
    {
     "title": "read_final_proc_time_ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "read_final_proc_time_ms",
       "legendFormat": "{{instance}} read_final_proc_time_ms-{{quantile}}"
      },
      {
       "expr": "read_final_proc_time_ms_count",
       "legendFormat": "{{instance}} read_final_proc_time_ms_count"
      },
      {
       "expr": "read_final_proc_time_ms_sum",
       "legendFormat": "{{instance}} read_final_proc_time_ms_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "updatelatency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "updatelatency",
       "legendFormat": "{{instance}} updatelatency-{{quantile}}"
      },
      {
       "expr": "updatelatency_count",
       "legendFormat": "{{instance}} updatelatency_count"
      },
      { "expr": "updatelatency_sum", "legendFormat": "{{instance}} updatelatency_sum" }
     ]
    },
    {
     "title": "max_min_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "max_latency", "legendFormat": "{{instance}} max_latency" },
      { "expr": "min_latency", "legendFormat": "{{instance}} min_latency" },
      { "expr": "avg_latency", "legendFormat": "{{instance}} avg_latency" }
     ]
    },
    {
     "title": "readlatency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "readlatency",
       "legendFormat": "{{instance}} readlatency-{{quantile}}"
      },
      { "expr": "readlatency_count", "legendFormat": "{{instance}} readlatency_count" },
      { "expr": "readlatency_sum", "legendFormat": "{{instance}} readlatency_sum" }
     ]
    },
    {
     "title": "propagation_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "propagation_latency",
       "legendFormat": "{{instance}} propagation_latency-{{quantile}}"
      },
      {
       "expr": "propagation_latency_count",
       "legendFormat": "{{instance}} propagation_latency_count"
      },
      {
       "expr": "propagation_latency_sum",
       "legendFormat": "{{instance}} propagation_latency_sum"
      }
     ]
    },
    {
     "title": "proposal_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "proposal_latency",
       "legendFormat": "{{instance}} proposal_latency-{{quantile}}"
      },
      {
       "expr": "proposal_latency_count",
       "legendFormat": "{{instance}} proposal_latency_count"
      },
      {
       "expr": "proposal_latency_sum",
       "legendFormat": "{{instance}} proposal_latency_sum"
      }
     ]
    },
    {
     "title": "commit_propagation_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "commit_propagation_latency",
       "legendFormat": "{{instance}}  commit_propagation_latency-{{quantile}}"
      },
      {
       "expr": "commit_propagation_latency_count",
       "legendFormat": "{{instance}} commit_propagation_latency_count"
      },
      {
       "expr": "commit_propagation_latency_sum",
       "legendFormat": "{{instance}} commit_propagation_latency_sum"
      }
     ]
    },
    {
     "title": "proposal_ack_creation_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "proposal_ack_creation_latency",
       "legendFormat": "{{instance}} proposal_ack_creation_latency-{{quantile}}"
      }
     ]
    },
    {
     "title": "ack_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ack_latency",
       "legendFormat": "{{instance}} ack_latency:{{key}}-{{quantile}}"
      },
      { "expr": "ack_latency_count", "legendFormat": "{{instance}} ack_latency_count" },
      { "expr": "ack_latency_sum", "legendFormat": "{{instance}} ack_latency_sum" }
     ]
    },
    {
     "title": "quorum_ack_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quorum_ack_latency",
       "legendFormat": "{{instance}} quorum_ack_latency-{{quantile}}"
      },
      {
       "expr": "quorum_ack_latency_count",
       "legendFormat": "{{instance}} quorum_ack_latency_count"
      },
      {
       "expr": "quorum_ack_latency_sum",
       "legendFormat": "{{instance}} quorum_ack_latency_sum"
      }
     ]
    },
    {
     "title": "commit_propagation_latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "commit_propagation_latency",
       "legendFormat": "{{instance}} commit_propagation_latency-{{quantile}}"
      },
      {
       "expr": "commit_propagation_latency_count",
       "legendFormat": "{{instance}} commit_propagation_latency_count"
      },
      {
       "expr": "commit_propagation_latency_sum",
       "legendFormat": "{{instance}} commit_propagation_latency_sum"
      }
     ]
    }
   ]
  }
 ]
}